### ISSUE TITLE
Accepting Contributions?

### ISSUE THREAD

**Issue by nenb** [jbusecke/cookiecutter-science-project#46]
Hey. This is a really nice template. I've been using it for a while to help students get started with Python, and it's worked really well!

There are a couple of issues that seem to arise quite regularly for students using the template. Some are straightforward to resolve (multiple environment.yml files, students get confused which one to use) and some can occasionally require a bit more time ('why can't I see the docs for my package'). There are also a couple of features that might be nice to add (e.g. pre-commit hooks).

Are you accepting contributions? If you are, I could open a bunch of pull requests. I have a sample contribution for pre-commit hooks here: https://github.com/nenb/cookiecutter-science-project/tree/pre-commit. I have a couple of others relating to publishing to conda-forge, adding the Jupyter Book feature, improving the docs, adding a Dockerfile, ... . Happy to discuss these all further!

**Comment by jbusecke** [comment]
Oh yeah for sure! I think a lot of these things should be optional. I do actually have some pre-commit hooks in there [already](https://github.com/jbusecke/cookiecutter-science-project/blob/master/%7B%7B%20cookiecutter.project_name.lower().replace('%20'%2C%20'_')%20%7D%7D/.pre-commit-config.yaml), but I would definitely appreciate some more instructions on how to activate the optional features!

But definitely open some issues/PRs! Id love to get some more contributions.

**Comment by nenb** [comment]
Great!

At the moment, most of the contributions are mandatory rather than optional. I don't think this should be too difficult to change though - probably best to figure out how in the comments on each Pull Request (and if you don't think that some of the contributions will work, that's fine too!).
