### ISSUE TITLE
Deprecating password authentication

### ISSUE THREAD

**Issue by lhoupert** [jbusecke/cookiecutter-science-project#5]
Hi all, do you have a fix for this issue:

https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

I generated a personal token but I am not sure what is the best way to modify the `setup.sh` file.

Should I just replaced
``` bash
curl -u '{{ cookiecutter.github_username }}' https://api.github.com/user/repos -d '{"name":"{{ cookiecutter.project_name.lower().replace(' ', '_') }}", "private":{{ cookiecutter.repo_private }}}'
```

by 
``` bash
curl -H 'Authorization: token '  {{ cookiecutter.github_accestoken}}  https://api.github.com/user/repos -d ...
```

After defining the ```cookiecutter.github_accestoken``` somewhere?

**Comment by jbusecke** [comment]
Hi @lhoupert, 

thanks for raising this issue. I am currently sifting through my gh inbox after vacation and am somewhat overwhelmed. Ill try to look into this in the next weeks. Sorry for the delay.

**Comment by lhoupert** [comment]
Hey @jbusecke ! No problem, I thought I should flag it up before someone get stuck

**Comment by jbusecke** [comment]
Thanks a lot. I'll try to look into it soon!

**Comment by jbusecke** [comment]
@lhoupert do you think this problem is sufficiently addressed by #6? I would have to look into the token, but am wondering if setting up an SSH key for github solves this issue for you?

**Comment by lhoupert** [comment]
Hi @jbusecke,
Interestingly I don't have this error message anymore!
I am not sure what happened.... I had my SSH key set-up since April.

**Comment by jbusecke** [comment]
Curious. Glad it works for you now. Feel free to reopen anytime. And thanks for using the template!
